# @name create-user
POST http://localhost:8080/users/
Content-Type: application/json

{
  "name": "Rodrigo Mendes Brocchi",
  "username": "rbrocchi",
  "password": "123456"
}

###

# @name create-task
POST http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic rbrocchi:123456

{
  "description": "Task test",
  "priority": "high",
  "title": "Create task test",
  "startedAt": "2023-10-13T12:00:00",
  "endAt": "2023-10-13T15:00:00"
}

###

# @name list-tasks
GET http://localhost:8080/tasks/
Content-Type: application/json
Authorization: Basic rbrocchi:123456

###

# @name update-task
PUT http://localhost:8080/tasks/d132da87-b68e-408a-a5fd-ea4ed48dd78a
Content-Type: application/json
Authorization: Basic rbrocchi:123456

{
  "description": "Task test",
  "priority": "low"
}

###